services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports: ["6333:6333", "6334:6334"]
    volumes:
      - ./qdrant_data:/qdrant/storage
      - ./qdrant_config:/qdrant/config

  indexer:
    build: .
    depends_on:
      qdrant:
        condition: service_started
    command: >
      bash -lc 'until curl -sf http://qdrant:6333/healthz >/dev/null; do sleep 1; done;
      python -m scripts.indexer'
    volumes:
      - ./:/app

  api:
    build: .
    depends_on:
      indexer:
        condition: service_completed_successfully
    ports: ["8000:8000"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./:/app
