name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            requirements*.txt
            pyproject.toml

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Ruff (lint)
        run: ruff check .

      - name: Ruff (format check)
        run: ruff format --check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      PYTHONDONTWRITEBYTECODE: 1
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            requirements*.txt
            pyproject.toml

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # se pytest não estiver no requirements.txt:
          pip install pytest

      - name: Run pytest
        run: python -m pytest -q

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx (cache opcional)
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t letrus-plagiarism-service .
